services:
  app:
    build: .
    volumes:
      - ./app:/app
      - .:/app:cached
      # ← Bind-mount the Windows folder directly (WSL path syntax):
      - /mnt/c/Users/mikko/Documents/Luomus/muuttolintujen_kevat/full:/data:cached
    environment:
      - FINBIF_API_TOKEN=move-to-env-file-and-exclude-with-gitignore
    stdin_open: true
    tty: true
