services:
  app:
    build: .
    volumes:
      - ./app:/app
      - .:/app:cached
      # ← Bind-mount the Windows folder directly (WSL path syntax):
      - /mnt/c/Users/mikko/Documents/Luomus/muuttolintujen_kevat/full:/data:cached
    environment:
      - FINBIF_API_TOKEN=test
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=testdb
      - MARIADB_USER=testuser
      - MARIADB_PASSWORD=testpass
    stdin_open: true
    tty: true
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=testdb
      - MARIADB_USER=testuser
      - MARIADB_PASSWORD=testpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: