services:
  app:
    build: .
    volumes:
      - ./app:/app
      - .:/app:cached
      # ← Bind-mount the Windows folder directly (WSL path syntax):
      - /mnt/c/Users/mikko/Documents/Luomus/muuttolintujen_kevat/full:/data:cached
    environment:
      - FINBIF_API_TOKEN=move-to-env-file-and-exclude-with-gitignore
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=testdb
      - MARIADB_USER=testuser
      - MARIADB_PASSWORD=testpass
      - MARIADB_HOST=mariadb
    stdin_open: true
    tty: true
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=testdb
      - MARIADB_USER=testuser
      - MARIADB_PASSWORD=testpass
      - MARIADB_HOST=mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=testuser
      - PMA_PASSWORD=testpass
    ports:
      - "8080:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data: